/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TestRouter__factory } from "./TestRouter__factory";
export { TestToken__factory } from "./TestToken__factory";
